### ISSUE TITLE
feat: user authentication

### ISSUE THREAD

**Issue by YouriLieverdink** [YouriLieverdink/horahora#21]
**Description**

We need some way of authenticating user so that they can use the API with their own account and data.

**Requirements**

- [x] Registration
- [x] Login
- [x] Delete all data

**Additional Context**

Add any other context or screenshots about the feature request go here.

**Comment by YouriLieverdink** [comment]
@QGIsK , do we also want to add the ability to authenticate using socials like Google, Facebook, etc.?

**Comment by QGIsK** [comment]
Would be nice to have eventually, but not a necessity for an mvp imo
